// Generated by CoffeeScript 1.7.1
(function() {
  var assert;

  assert = require('assert');

  suite('Deb.js', function() {
    return test('Environment Setup', function(done, server, client) {
      client["eval"](function() {
        return Meteor.startup(function() {
          return emit('isDebExist', _.every([typeof deb !== "undefined" && deb !== null, typeof debc !== "undefined" && debc !== null, Function.deb != null, Function.debc != null, window.deb != null, window.debc != null]));
        });
      });
      return client.once('isDebExist', function(expectTrue) {
        assert(expectTrue);
        return done();
      });
    });
  });

}).call(this);
